apiVersion: apps/v1
kind: Deployment
metadata:
   name: movies
spec:
   selector:
       matchLabels:
           app: movies
   template:
       metadata:
           labels:
               app: movies
       spec:
           containers:
             - name: movies
               image: creativti/rotten-potatoes:v1
               ports:
                 - containerPort: 8080
               env:
                 - name: MONGODB_DB
                   value: admin
                 - name: MONGODB_HOST
                   value: mongodbservice
                 - name: MONGODB_PORT
                   value: "27017"
                 - name: MONGODB_USERNAME
                   value: mongouser
                 - name: MONGODB_PASSWORD
                   value: mongopwd
               resources:
                   requests:
                       cpu: "200m"
                       memory: "32Mi"
                   limits:
                       cpu: "400m"
                       memory: "64Mi"
